apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerry-app
  labels:
    app: jerry-app
    culprit: jerry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jerry-app
  template:
    metadata:
      labels:
        app: jerry-app
    spec:
      containers:
        - name: memory-hog
          image: polinux/stress
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "128M", "--vm-hang", "1"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
