apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerry-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jerry-web
  template:
    metadata:
      labels:
        app: jerry-web
        version: v1
        team: jerry
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "<html><body><h1>Jerry's App</h1><p>Pod: $HOSTNAME</p></body></html>" > /usr/share/nginx/html/index.html
            nginx -g 'daemon off;'